Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provision :shell, path: "scripts/nginx.sh"
  config.vm.network "private_network", ip: "192.168.50.100"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 22, host: 2222
  
end
